[general]
live_config_reload = true
import = ["alacritty-theme/themes/gruvbox_dark.toml"]

[window]
blur = true
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
opacity = 0.8

[font]
normal = { family = "Fira Code Nerd Font" }

# [terminal]
# shell = "zellij"

