format = """
$username\
$directory\
[](fg:#32302f bg:#3c3836)\
$git_branch\
$git_status\
[](fg:#3c3836 bg:#504945)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#504945 bg:#665c54)\
$docker_context\
[](fg:#665c54 bg:#7c6f64)\
$battery\
[](fg:#7c6f64 bg:#458588)\
$time\
[ ](fg:#458588)\
\n   
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "#d65d0e"
style_root = "#cc241d"
format = '[]($style)[$user ](bg:$style)[](fg:$style bg:#32302f)'

[directory]
style = "bg:#32302f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[docker_context]
symbol = " "
style = "bg:#665c54"
format = '[[ $symbol $context ](bg:#458588)]($style) $path'

[elixir]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[elm]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[git_branch]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol $branch ](bg:#3c3836)]($style)'

[git_status]
style = "bg:#3c3836"
format = '[[($all_status$ahead_behind )](bg:#3c3836)]($style)'

[golang]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[haskell]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[julia]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nim]
symbol = " "
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%H:%M" # Hour:Minute Format
style = "bg:#7c6f64"
format = '[[ $time ](bg:#458588)]($style)'

[battery]
full_symbol = "   "
charging_symbol = "  "
format= "[$symbol$percentage ]($style)"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
discharging_symbol =  "   "
style = " bg:#7c6f64"

[[battery.display]]  # "bold orange"  style when capacity is between 10% and 30%
threshold = 30
discharging_symbol =  "   "
style = "bg:#7c6f64"

[[battery.display]]  # "bold yellow" style when capacity is between 30% and 50%
threshold = 50
discharging_symbol =  "   "
style = "bg:#7c6f64"

[[battery.display]]  # "ice " style when capacity is between 50% and 70%
threshold = 70
discharging_symbol =  "   "
style = "bg:#7c6f64"

[[battery.display]]  # " Green " style when capacity is between 70% and 90%
threshold = 90
discharging_symbol =  "   "
style = "bg:#7c6f64"

[[battery.display]]  # "White " style when capacity is between 90% and 100%
threshold = 100
style = "bg:#7c6f64"
